# Numpy

In [ ]:
import numpy as np

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [ ]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [ ]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [ ]:
np.ones(100) * 3

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

#### 4. Как получить документацию о функции numpy.add из командной строки?

python -c "import numpy; numpy.info(numpy.add)"

#### 5. Поменять 2 строки в матрице

In [ ]:
x = np.eye(2)
print("Было:")
print(x)
x[[0, 1]] = x[[1, 0]]
print("Стало:")
print(x)

Было:
[[1. 0.]
 [0. 1.]]
Стало:
[[0. 1.]
 [1. 0.]]


#### 6. Создать вектор со значениями от 10 до 100

In [ ]:
np.arange(10, 101)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [ ]:
np.arange(10, 101)[::-1]

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [ ]:
np.arange(16).reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.zeros(len(x) + 12)
y[::4] = x
y

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 10. Создать 3x3 единичную матрицу

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [ ]:
np.random.random((3,3,3))

array([[[0.8464297 , 0.74482227, 0.13584008],
        [0.20578636, 0.62273486, 0.80334403],
        [0.85815587, 0.08548948, 0.60861387]],

       [[0.42341763, 0.40180163, 0.30824172],
        [0.91843798, 0.66854007, 0.65936429],
        [0.04325978, 0.8167495 , 0.83643856]],

       [[0.80177058, 0.8259894 , 0.64711492],
        [0.43323289, 0.20641268, 0.29574515],
        [0.6878977 , 0.21105208, 0.89252241]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [ ]:
x = np.random.random((10, 10))
x.min(), x.max()

(0.0010768183868159475, 0.9953534723478519)

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [ ]:
x = np.random.random(30)
x.mean()

0.40782195794217974

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [ ]:
x = np.zeros((10, 10))
x[1:-1, 1:-1] = 1
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

Не знаю насколько классное, но полезное)

In [ ]:
x = np.arange(10)

func = np.vectorize(lambda x: x ** 3)
func(x)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [ ]:
np.diag(np.array([1, 2, 2, 4]), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [ ]:
x = np.ones((8, 8), dtype=int)
x[1::2, ::2] = 0
x[::2, 1::2] = 0
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [ ]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [ ]:
first = np.tile(np.array([0, 1]), 4)
second = np.tile(np.array([1, 0]), 4)
x = []

for i in range(4):
  x.append(first)
  x.append(second)
np.array(x)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [ ]:
a = np.ones((5,3)) @ np.ones((3,2))
b = np.dot(np.ones((5,3)), np.ones((3,2)))
a, b

(array([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]]), array([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]]))

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
x = np.random.random(50) * 20
x[(3 <= x) & (x <= 8)] *= -1
x

array([-5.22770087,  8.29012059, 17.58550785, -7.39420114,  9.22482071,
       12.59679096,  0.57950349, -6.22667271, -6.14235256,  0.90040879,
       11.03816648, 13.72841705, 16.20305671, 12.1214941 ,  9.24237503,
       -4.80179528, -6.99396389, 13.52627551, 14.24528993,  9.83386834,
       12.20077365,  9.94158479, -7.93034739, 14.31643876, 13.67401966,
       17.65357418, -3.9453233 , 12.16250321, 15.60247401, 14.2626548 ,
       14.58109943, 10.42693155, 18.24801685, 16.36206263, 17.64007805,
       16.4603403 , -7.59348009, -4.22770961,  1.57252029, 11.85903127,
       -7.14719906,  2.11545288, -4.32570495,  9.5330654 , 12.73662617,
       16.20087387, 13.97592381, 17.08178084, 15.00309953, -5.80659927])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [ ]:
np.zeros((5,5), dtype=int) + np.arange(5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 24. Есть генератор, сделать с его помощью массив

In [ ]:
def np_generate():
    for x in range(10):
        yield x ** 3
x = np.fromiter(np_generate(), dtype=int)
x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [ ]:
np.linspace(0,1,12)[1:11]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 26. Отсортировать вектор

In [ ]:
x = np.random.random(50)
x.sort()
x

array([0.00217023, 0.00356828, 0.02126188, 0.02178495, 0.0381462 ,
       0.1269536 , 0.13337016, 0.13635068, 0.1460334 , 0.15466336,
       0.18513526, 0.19839243, 0.19860573, 0.19980435, 0.21679928,
       0.21857812, 0.2339546 , 0.23520287, 0.25297685, 0.36163255,
       0.37844886, 0.40958058, 0.43016939, 0.44095239, 0.45378304,
       0.48514779, 0.49401388, 0.51466   , 0.52638742, 0.55617506,
       0.59166726, 0.63455059, 0.64185231, 0.65015632, 0.65034451,
       0.66758747, 0.68373333, 0.6848894 , 0.70066954, 0.74597576,
       0.75928351, 0.77574577, 0.79118954, 0.79473884, 0.81014344,
       0.85250027, 0.85911877, 0.92915529, 0.94665239, 0.96422224])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

np.allclose(a, b)

True

#### 28. Сделать массив неизменяемым

In [ ]:
x = np.random.random(50)
x.flags.writeable = False

#### 29. Найти n наибольших значений в массиве

In [ ]:
n = 10
x = np.random.random(50)
x.sort()
x, x[-n:]

(array([0.00505984, 0.0549295 , 0.05696204, 0.10564042, 0.13814157,
        0.14123496, 0.15606687, 0.16560843, 0.17689476, 0.20007732,
        0.20023255, 0.2076977 , 0.22176158, 0.23959332, 0.240516  ,
        0.25262109, 0.27390331, 0.30608891, 0.30694556, 0.31180881,
        0.33131204, 0.33381028, 0.34283605, 0.36479299, 0.36635921,
        0.40334255, 0.40349742, 0.43003962, 0.43507745, 0.45400761,
        0.47174681, 0.47775756, 0.48528135, 0.49611509, 0.52413641,
        0.57897525, 0.62212419, 0.66131431, 0.68209266, 0.74120088,
        0.75356613, 0.76356719, 0.7652845 , 0.78270939, 0.82987296,
        0.86102824, 0.8758043 , 0.90164337, 0.94352379, 0.98568294]),
 array([0.75356613, 0.76356719, 0.7652845 , 0.78270939, 0.82987296,
        0.86102824, 0.8758043 , 0.90164337, 0.94352379, 0.98568294]))

#### 30. Заменить максимальный элемент на ноль

In [ ]:
x = np.random.random(50)
x[x.argmax()] = 0
x

array([0.33996699, 0.85755604, 0.87289536, 0.71777551, 0.48499372,
       0.52467536, 0.79930672, 0.64174386, 0.09978734, 0.21641384,
       0.45534069, 0.08720935, 0.95544516, 0.75775097, 0.52242356,
       0.36190191, 0.80465902, 0.56994173, 0.26368483, 0.76928087,
       0.8647199 , 0.52176562, 0.72211336, 0.9205544 , 0.35759011,
       0.81871357, 0.75259042, 0.        , 0.52237964, 0.00811203,
       0.39200764, 0.16611557, 0.49318884, 0.79933711, 0.94709257,
       0.38887085, 0.86437163, 0.16368826, 0.10994173, 0.17713717,
       0.32279419, 0.72266973, 0.64201228, 0.37439624, 0.09114396,
       0.10935054, 0.31398564, 0.48617406, 0.79375819, 0.37983204])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [ ]:
np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))

[array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [0.        , 0.1111

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

z = 1 / np.array([(a - b) for a in x for b in y]).reshape([x.size, y.size])
z

array([[-0.33333333, -0.25      , -0.2       ],
       [-0.5       , -0.33333333, -0.25      ],
       [-1.        , -0.5       , -0.33333333]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [ ]:
print("INT")
for int_type in (np.int8, np.int16, np.int32, np.intc, np.int, np.integer, 
                 np.int0, np.int64, np.int_):
  print(int_type)
  print(f"[{np.iinfo(int_type).min}; {np.iinfo(int_type).max}]")

print("\n\nFLOAT")
for float_type in (np.float16, np.float32, np.float64, np.float_, 
                   np.float, np.floating, np.float128):
  print(float_type)
  print(f"[{np.finfo(float_type).min}; {np.finfo(float_type).max}]")


INT
<class 'numpy.int8'>
[-128; 127]
<class 'numpy.int16'>
[-32768; 32767]
<class 'numpy.int32'>
[-2147483648; 2147483647]
<class 'numpy.int32'>
[-2147483648; 2147483647]
<class 'int'>
[-9223372036854775808; 9223372036854775807]
<class 'numpy.integer'>
[-9223372036854775808; 9223372036854775807]
<class 'numpy.int64'>
[-9223372036854775808; 9223372036854775807]
<class 'numpy.int64'>
[-9223372036854775808; 9223372036854775807]
<class 'numpy.int64'>
[-9223372036854775808; 9223372036854775807]


FLOAT
<class 'numpy.float16'>
[-65504.0; 65504.0]
<class 'numpy.float32'>
[-3.4028234663852886e+38; 3.4028234663852886e+38]
<class 'numpy.float64'>
[-1.7976931348623157e+308; 1.7976931348623157e+308]
<class 'numpy.float64'>
[-1.7976931348623157e+308; 1.7976931348623157e+308]
<class 'float'>
[-1.7976931348623157e+308; 1.7976931348623157e+308]
<class 'numpy.floating'>
[-1.7976931348623157e+308; 1.7976931348623157e+308]
<class 'numpy.float128'>
[-inf; inf]


#### 34. Напечатать все значения в массиве

In [ ]:
x = np.random.random(50)
x[49] = np.nan
print(x)

[0.56851095 0.18611731 0.07307531 0.66396224 0.29352175 0.26161694
 0.31706528 0.35211677 0.99616689 0.34941653 0.11687967 0.88332695
 0.55673787 0.97256471 0.51044868 0.3074281  0.63189924 0.09267666
 0.30361702 0.85180965 0.60990922 0.25020262 0.51421104 0.04769334
 0.43308558 0.42036825 0.59822371 0.95585792 0.5235529  0.61031767
 0.06482475 0.47317203 0.57295656 0.54961085 0.64475166 0.83997482
 0.9758864  0.30452605 0.73265708 0.95145237 0.91299483 0.24795595
 0.67289428 0.00488226 0.19722025 0.18452189 0.66778316 0.43387623
 0.9441599         nan]


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
x = np.random.random(50) * 20
y = 5
x[np.abs(x - y).argmin()]

4.812371318035629

#### 36. Преобразовать массив из float в int

In [ ]:
x = np.random.random(50).astype(dtype=int)
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [ ]:
x = np.random.random(5)
for i, v in np.ndenumerate(x):
  print(i, v)

(0,) 0.2159470705723321
(1,) 0.10996139541884642
(2,) 0.385992642234424
(3,) 0.014960377032295913
(4,) 0.9218975403808896


#### 38. Случайно расположить p элементов в 2D массив

In [ ]:
x = np.zeros((5, 5), dtype=int) # исходный массив (25 элементов)
p = np.arange(5, 25) # p элементов, которые располагаем в массиве x (20 элементов)

indexes = np.arange(x.size)
del_indexes = np.copy(indexes)
np.random.shuffle(del_indexes)
del_indexes = del_indexes[:x.size - p.size]

indexes = np.delete(indexes, del_indexes)
np.put(x, indexes, p)
x

array([[ 5,  6,  0,  7,  8],
       [ 9, 10, 11, 12, 13],
       [14, 15,  0, 16, 17],
       [18,  0, 19, 20, 21],
       [22,  0, 23,  0, 24]])

#### 39. Отнять среднее из каждой строки в матрице

In [ ]:
x = np.random.random((5, 5)) * 20
print(x)
# print(x.mean(axis=1)) для проверки
y = x - x.mean(axis=1, keepdims=True)
y

[[14.20783775 11.9006082  16.60610139  6.91081815 13.69961866]
 [12.723444    1.66930775 14.90379071 18.29890238  3.51822086]
 [ 1.11677177 13.64035541 19.41951431 16.48001167  7.03521849]
 [ 7.72320659  8.08329076 10.29049542 17.16566158 14.68383137]
 [ 2.1275363   4.09207729 15.42611309 11.62070711 19.45014282]]


array([[  1.54284092,  -0.76438863,   3.94110456,  -5.75417868,
          1.03462183],
       [  2.50071086,  -8.55342539,   4.68105757,   8.07616924,
         -6.70451228],
       [-10.42160256,   2.10198108,   7.88113998,   4.94163734,
         -4.50315584],
       [ -3.86609056,  -3.50600638,  -1.29880173,   5.57636444,
          3.09453423],
       [ -8.41577902,  -6.45123803,   4.88279777,   1.07739179,
          8.9068275 ]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [ ]:
def np_sort(x, n):
  return x[x[:, (n - 1)].argsort()]

x = np.random.random((5, 5)) * 20
print(x)
np_sort(x, 1)

[[10.67071664 19.17663496  8.04937098 10.615065   19.58583754]
 [16.64874406  1.95406659  9.27459536  1.25148146  4.53203862]
 [ 4.22744473 10.75604276  2.11113472 13.71042656  2.89564292]
 [12.01848298  6.69783579 16.08636398 18.28488935 19.24382485]
 [ 3.15836634 15.47422485 15.95430748 15.3386498  15.12360711]]


array([[ 3.15836634, 15.47422485, 15.95430748, 15.3386498 , 15.12360711],
       [ 4.22744473, 10.75604276,  2.11113472, 13.71042656,  2.89564292],
       [10.67071664, 19.17663496,  8.04937098, 10.615065  , 19.58583754],
       [12.01848298,  6.69783579, 16.08636398, 18.28488935, 19.24382485],
       [16.64874406,  1.95406659,  9.27459536,  1.25148146,  4.53203862]])

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [ ]:
def is_zero_col(x):
  zero_index = np.argwhere(np.all(x == 0, axis=0))
  return True if len(zero_index) != 0 else False

x = np.array([np.array([1, 2, 3, 0]),
              np.array([1, 5, 6, 0]),
              np.array([-1, 0, 9, 0])])
is_zero_col(x)

True

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [ ]:
x = np.arange(10)
indexes = np.arange(1, 11, 2)

for i in indexes:
  x[i] += 1
x

array([ 0,  2,  2,  4,  4,  6,  6,  8,  8, 10])

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [ ]:
def unique(w, h):
  x = np.random.randint(0, 255, (w, h, 3))
  x.astype(np.ubyte)
  print(x)
  value_unique, count_unique = np.unique(x, return_counts=True)
  return count_unique.shape[0]

unique(5, 5)

[[[ 17  66 178]
  [ 94  42   8]
  [ 27  15 231]
  [212 186  68]
  [235  56 172]]

 [[206 144 118]
  [227   0  65]
  [211  50 142]
  [198 218 119]
  [108 126 181]]

 [[ 50 187 170]
  [ 34 198 250]
  [102  43 219]
  [ 70  46 178]
  [ 87 140   6]]

 [[209 197 208]
  [208  23  62]
  [189  60  98]
  [ 98 194 226]
  [ 58 121  61]]

 [[221  54  19]
  [ 47  74  26]
  [188 103 116]
  [ 48 188  36]
  [  7 210 150]]]


69

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям